require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BabycardsController do

  # This should return the minimal set of attributes required to create a valid
  # Babycard. As you add validations to Babycard, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BabycardsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all babycards as @babycards" do
      babycard = Babycard.create! valid_attributes
      get :index, {}, valid_session
      assigns(:babycards).should eq([babycard])
    end
  end

  describe "GET show" do
    it "assigns the requested babycard as @babycard" do
      babycard = Babycard.create! valid_attributes
      get :show, {:id => babycard.to_param}, valid_session
      assigns(:babycard).should eq(babycard)
    end
  end

  describe "GET new" do
    it "assigns a new babycard as @babycard" do
      get :new, {}, valid_session
      assigns(:babycard).should be_a_new(Babycard)
    end
  end

  describe "GET edit" do
    it "assigns the requested babycard as @babycard" do
      babycard = Babycard.create! valid_attributes
      get :edit, {:id => babycard.to_param}, valid_session
      assigns(:babycard).should eq(babycard)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Babycard" do
        expect {
          post :create, {:babycard => valid_attributes}, valid_session
        }.to change(Babycard, :count).by(1)
      end

      it "assigns a newly created babycard as @babycard" do
        post :create, {:babycard => valid_attributes}, valid_session
        assigns(:babycard).should be_a(Babycard)
        assigns(:babycard).should be_persisted
      end

      it "redirects to the created babycard" do
        post :create, {:babycard => valid_attributes}, valid_session
        response.should redirect_to(Babycard.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved babycard as @babycard" do
        # Trigger the behavior that occurs when invalid params are submitted
        Babycard.any_instance.stub(:save).and_return(false)
        post :create, {:babycard => { "name" => "invalid value" }}, valid_session
        assigns(:babycard).should be_a_new(Babycard)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Babycard.any_instance.stub(:save).and_return(false)
        post :create, {:babycard => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested babycard" do
        babycard = Babycard.create! valid_attributes
        # Assuming there are no other babycards in the database, this
        # specifies that the Babycard created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Babycard.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => babycard.to_param, :babycard => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested babycard as @babycard" do
        babycard = Babycard.create! valid_attributes
        put :update, {:id => babycard.to_param, :babycard => valid_attributes}, valid_session
        assigns(:babycard).should eq(babycard)
      end

      it "redirects to the babycard" do
        babycard = Babycard.create! valid_attributes
        put :update, {:id => babycard.to_param, :babycard => valid_attributes}, valid_session
        response.should redirect_to(babycard)
      end
    end

    describe "with invalid params" do
      it "assigns the babycard as @babycard" do
        babycard = Babycard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Babycard.any_instance.stub(:save).and_return(false)
        put :update, {:id => babycard.to_param, :babycard => { "name" => "invalid value" }}, valid_session
        assigns(:babycard).should eq(babycard)
      end

      it "re-renders the 'edit' template" do
        babycard = Babycard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Babycard.any_instance.stub(:save).and_return(false)
        put :update, {:id => babycard.to_param, :babycard => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested babycard" do
      babycard = Babycard.create! valid_attributes
      expect {
        delete :destroy, {:id => babycard.to_param}, valid_session
      }.to change(Babycard, :count).by(-1)
    end

    it "redirects to the babycards list" do
      babycard = Babycard.create! valid_attributes
      delete :destroy, {:id => babycard.to_param}, valid_session
      response.should redirect_to(babycards_url)
    end
  end

end
