require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PageSectionsController do

  # This should return the minimal set of attributes required to create a valid
  # PageSection. As you add validations to PageSection, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "page_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PageSectionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all page_sections as @page_sections" do
      page_section = PageSection.create! valid_attributes
      get :index, {}, valid_session
      assigns(:page_sections).should eq([page_section])
    end
  end

  describe "GET show" do
    it "assigns the requested page_section as @page_section" do
      page_section = PageSection.create! valid_attributes
      get :show, {:id => page_section.to_param}, valid_session
      assigns(:page_section).should eq(page_section)
    end
  end

  describe "GET new" do
    it "assigns a new page_section as @page_section" do
      get :new, {}, valid_session
      assigns(:page_section).should be_a_new(PageSection)
    end
  end

  describe "GET edit" do
    it "assigns the requested page_section as @page_section" do
      page_section = PageSection.create! valid_attributes
      get :edit, {:id => page_section.to_param}, valid_session
      assigns(:page_section).should eq(page_section)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PageSection" do
        expect {
          post :create, {:page_section => valid_attributes}, valid_session
        }.to change(PageSection, :count).by(1)
      end

      it "assigns a newly created page_section as @page_section" do
        post :create, {:page_section => valid_attributes}, valid_session
        assigns(:page_section).should be_a(PageSection)
        assigns(:page_section).should be_persisted
      end

      it "redirects to the created page_section" do
        post :create, {:page_section => valid_attributes}, valid_session
        response.should redirect_to(PageSection.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved page_section as @page_section" do
        # Trigger the behavior that occurs when invalid params are submitted
        PageSection.any_instance.stub(:save).and_return(false)
        post :create, {:page_section => { "page_id" => "invalid value" }}, valid_session
        assigns(:page_section).should be_a_new(PageSection)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PageSection.any_instance.stub(:save).and_return(false)
        post :create, {:page_section => { "page_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested page_section" do
        page_section = PageSection.create! valid_attributes
        # Assuming there are no other page_sections in the database, this
        # specifies that the PageSection created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PageSection.any_instance.should_receive(:update_attributes).with({ "page_id" => "1" })
        put :update, {:id => page_section.to_param, :page_section => { "page_id" => "1" }}, valid_session
      end

      it "assigns the requested page_section as @page_section" do
        page_section = PageSection.create! valid_attributes
        put :update, {:id => page_section.to_param, :page_section => valid_attributes}, valid_session
        assigns(:page_section).should eq(page_section)
      end

      it "redirects to the page_section" do
        page_section = PageSection.create! valid_attributes
        put :update, {:id => page_section.to_param, :page_section => valid_attributes}, valid_session
        response.should redirect_to(page_section)
      end
    end

    describe "with invalid params" do
      it "assigns the page_section as @page_section" do
        page_section = PageSection.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PageSection.any_instance.stub(:save).and_return(false)
        put :update, {:id => page_section.to_param, :page_section => { "page_id" => "invalid value" }}, valid_session
        assigns(:page_section).should eq(page_section)
      end

      it "re-renders the 'edit' template" do
        page_section = PageSection.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PageSection.any_instance.stub(:save).and_return(false)
        put :update, {:id => page_section.to_param, :page_section => { "page_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested page_section" do
      page_section = PageSection.create! valid_attributes
      expect {
        delete :destroy, {:id => page_section.to_param}, valid_session
      }.to change(PageSection, :count).by(-1)
    end

    it "redirects to the page_sections list" do
      page_section = PageSection.create! valid_attributes
      delete :destroy, {:id => page_section.to_param}, valid_session
      response.should redirect_to(page_sections_url)
    end
  end

end
